esphome:
  name: liquidlevel-op-example
  friendly_name: liquidlevel-op-example

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***********************************"

# Enable OTA updates
ota:
  password: "***********************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "liquidlevel-op-example"
    password: "*********"

captive_portal:

binary_sensor:
  - platform: gpio
    pin: 4
    name: "liquidlevel-onepoint"
    filters:
      - invert:
      - delayed_on: 100ms
      - delayed_off: 100ms