esphome:
  name: liquidlevel-fp-example
  friendly_name: liquidlevel-fp-example
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***********************************"

# Enable OTA updates
ota:
  password: "***********************"

# Configure WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "liquidlevel-fp-example"
    password: "*********"

captive_portal:

#Configure pulse meter sensor
sensor:
  - platform: pulse_meter
    pin: 4
    name: "liquidlevel-fourpoint"
    unit_of_measurement: "Level"
    filters:
      # Lambda function to map pulse values to liquid levels
      - lambda: !lambda |-
          if (x < 2000.0) return 0.0;
          if (x < 4000.0) return 1.0;
          if (x < 8000.0) return 2.0;
          if (x < 13000.0) return 3.0;
          return 4.0;
      - round: 1
      - or:
        - delta: 0.9
        - throttle: 30s
    